---
title: "Modern Portfolio Optimization (case 1)"
output: html_document
date: "2022-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Loading libraries
# Core
library(tidyverse)
## Finance analytics
library(tidyquant)
# Optimization Solving
library(quadprog)
# Visualization 
library(plotly)
```

```{r}
### Getting data 
stock <- c("AAPL", "META", "OXY", "SE", "TSLA")
data <- tq_get(stock, get = "stock.prices", complete_cases = TRUE, from = "2017-01-01", to = TODAY())
returns_data <- data %>%
    select(symbol, date, adjusted) %>%
    group_by(symbol)%>%
    tq_transmute(adjusted, 
                 mutate_fun = periodReturn, 
                 period = "yearly", 
                 col_rename = "Annual Return")
returns_data %>%
   pivot_wider(names_from = 'symbol',values_from = 'Annual Return')
```

```{r}
## Securities Statistics
### Individual security
stats <- returns_data %>%
  summarise(
    Expected_Annual_Return = mean(`Annual Return`),
    Standard_Deviation = sd(`Annual Return`)
  )
stats
```

```{r}

### Covariance
returns_matrix <- tidyr::spread(returns_data, 
                                key = "symbol", 
                                value = "Annual Return")
covariance_matrix <- cov(returns_matrix[,-1])
covariance_matrix
```

```{r}
## Optimization Solving
### Quadratic Programming Setup 
# Objective matrix
Dmat <- 2*covariance_matrix
#Objective vector
dvec <- c(0,0,0,0,0)
# Constraint Matrix
Amat <- t(matrix(c(1, as.numeric(stats[stats$symbol == "AAPL", "Expected_Annual_Return"]),1,0,0,0,0,
                   1,as.numeric(stats[stats$symbol == "META", "Expected_Annual_Return"]),0,1,0,0,0,
                   1,as.numeric(stats[stats$symbol == "OXY", "Expected_Annual_Return"]),0,0,1,0,0,
                   1,as.numeric(stats[stats$symbol == "SE", "Expected_Annual_Return"]),0,0,0,1,0,
                   1,as.numeric(stats[stats$symbol == "TSLA", "Expected_Annual_Return"]),0,0,0,0,1),7,5))
# Require Return (Set at 0.5)
goal <- 0.5 # Desirable return
# Right hand side
bvec <- c(1,goal,0,0,0,0,0)

### Quadratic Programming Solving
qp <- solve.QP(Dmat, 
               dvec, 
               Amat, 
               bvec, 
               meq = 1)
portfolio_weights <- rbind(stock, round(qp$solution, 4))
portfolio_weights
portfolio_variance <- qp$value
portfolio_variance
```

```{r}
### For checking result only
calc_portfolio_variance <- function(weights) {
    t(weights) %*% (covariance_matrix %*% weights) %>% as.vector()
}
calc_portfolio_variance(qp$solution) #Should equals to portfolio_covariance
calc_portfolio_return <- function(weights) {
    stats_mean <- stats$Expected_Annual_Return
    sum(stats_mean * weights)
}
calc_portfolio_return(qp$solution) #Should equals to the desirable return.
```

```{r}
###Visualization
port_return <- c()
port_variance <-c()
min_return_in_percent <- ceiling(min(stats$Expected_Annual_Return)*100)
max_return_in_percent <- floor(max(stats$Expected_Annual_Return)*100)
for (n in (min_return_in_percent:max_return_in_percent)){
  expected_portfolio_return <- n/100
  new_bvec <- c(1,expected_portfolio_return,0,0,0,0,0)
  qp <- solve.QP(Dmat, dvec, Amat, new_bvec, meq = 1)
  port_return <- c(port_return, expected_portfolio_return)
  port_variance <- c(port_variance, qp$value)
}
efficient_frontier <- plot_ly(x = port_variance, 
                              y = port_return,
                              type = 'scatter',
                              mode = 'lines+markers',
                              fill = 'tozeroy')%>%
  layout(title = "Efficient Frontier", xaxis = list(title = "Portfolio Variance (Risk)"), yaxis = list(title = "Portfolio Return"))
efficient_frontier
```
